### ISSUE TITLE
poetry removes setuptools

### ISSUE THREAD

**Issue by inktrap** [sloth-ci/sloth-ci#2]
Fresh installation of develop branch via poetry fails, basicly poetry removes setuptools but wrapt needs it:

```
vh@box ~ [i] % mkdir ci
vh@box ~ [i] % cd ci 
vh@box ~/ci [i] % git clone https://github.com/sloth-ci/sloth-ci
Cloning into 'sloth-ci'...
remote: Enumerating objects: 4785, done.
remote: Counting objects: 100% (4785/4785), done.
remote: Compressing objects: 100% (1885/1885), done.
remote: Total 4785 (delta 3012), reused 4573 (delta 2803), pack-reused 0
Receiving objects: 100% (4785/4785), 2.50 MiB | 6.00 MiB/s, done.
Resolving deltas: 100% (3012/3012), done.
vh@box ~/ci [i] % cd sloth-ci 
vh@box ~/ci/sloth-ci [develop][i] % poetry install
Creating virtualenv sloth-ci-gF8KaH2q-py3.9 in /home/vh/.cache/pypoetry/virtualenvs
Installing dependencies from lock file

Package operations: 62 installs, 0 updates, 1 removal

  • Removing setuptools (57.4.0)
  • Installing six (1.16.0)
  • Installing wcwidth (0.2.5)
  • Installing cliar (1.3.4)
  • Installing more-itertools (8.8.0)
  • Installing prompt-toolkit (2.0.10)
  • Installing pyyaml (5.4.1)
  • Installing contextlib2 (21.6.0)
  • Installing foliant (1.0.12)
  • Installing jaraco.functools (3.3.0)
  • Installing markupsafe (2.0.1)
  • Installing pyparsing (2.4.7)
  • Installing python-dateutil (2.8.2)
  • Installing pytz (2021.1)
  • Installing zipp (3.5.0)
  • Installing click (8.0.1)
  • Installing foliantcontrib.utils (1.0.2)
  • Installing ghp-import (2.0.1)
  • Installing importlib-metadata (4.6.1)
  • Installing jaraco.classes (3.2.1)
  • Installing jaraco.text (3.5.1)
  • Installing jinja2 (3.0.1)
  • Installing lazy-object-proxy (1.6.0)
  • Installing markdown (3.3.4)
  • Installing mergedeep (1.3.4)
  • Installing packaging (21.0)
  • Installing pyyaml-env-tag (0.1)
  • Installing schema (0.7.4)
  • Installing tempora (4.1.1)
  • Installing text-unidecode (1.3)
  • Installing watchdog (2.1.3)
  • Installing wrapt (1.12.1): Failed

  EnvCommandError

  Command ['/home/vh/.cache/pypoetry/virtualenvs/sloth-ci-gF8KaH2q-py3.9/bin/pip', 'install', '--no-deps', 'file:///home/vh/.cache/pypoetry/artifacts/6c/e2/d9/2c022794d212a87320efa16fd1b05654bf6656b6cf0510c072845ecc95/wrapt-1.12.1.tar.gz'] errored with the following return code 1, and output: 
  Processing /home/vh/.cache/pypoetry/artifacts/6c/e2/d9/2c022794d212a87320efa16fd1b05654bf6656b6cf0510c072845ecc95/wrapt-1.12.1.tar.gz
      ERROR: Command errored out with exit status 1:
       command: /home/vh/.cache/pypoetry/virtualenvs/sloth-ci-gF8KaH2q-py3.9/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-9rj2ojhh/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-9rj2ojhh/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-r2eueice
           cwd: /tmp/pip-req-build-9rj2ojhh/
      Complete output (3 lines):
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
      ModuleNotFoundError: No module named 'setuptools'
      ----------------------------------------
  WARNING: Discarding file:///home/vh/.cache/pypoetry/artifacts/6c/e2/d9/2c022794d212a87320efa16fd1b05654bf6656b6cf0510c072845ecc95/wrapt-1.12.1.tar.gz. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  WARNING: You are using pip version 21.0.1; however, version 21.3 is available.
  You should consider upgrading via the '/home/vh/.cache/pypoetry/virtualenvs/sloth-ci-gF8KaH2q-py3.9/bin/python -m pip install --upgrade pip' command.
  

  at ~/.local/lib/python3.9/site-packages/poetry/utils/env.py:1101 in _run
      1097│                 output = subprocess.check_output(
      1098│                     cmd, stderr=subprocess.STDOUT, **kwargs
      1099│                 )
      1100│         except CalledProcessError as e:
    → 1101│             raise EnvCommandError(e, input=input_)
      1102│ 
      1103│         return decode(output)
      1104│ 
      1105│     def execute(self, bin, *args, **kwargs):
```

**Comment by inktrap** [comment]
Installing from ``master`` works, so I would suggest to either add a note in the docs or fix it or both. :)
However, then I still can't build the docs, because of missing setuptools, only if I install it manually:

```
vh@box ~/ci/sloth-ci [master][i] % poetry run foliant make site -p docs
Traceback (most recent call last):
  File "/home/vh/.cache/pypoetry/virtualenvs/sloth-ci-gF8KaH2q-py3.9/bin/foliant", line 5, in <module>
    from foliant.cli import entry_point
  File "/home/vh/.cache/pypoetry/virtualenvs/sloth-ci-gF8KaH2q-py3.9/lib/python3.9/site-packages/foliant/cli/__init__.py", line 7, in <module>
    from foliant.utils import get_available_clis
  File "/home/vh/.cache/pypoetry/virtualenvs/sloth-ci-gF8KaH2q-py3.9/lib/python3.9/site-packages/foliant/utils.py", line 11, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
vh@box ~/ci/sloth-ci [master][n] % poetry run pip install setuptools              1

Collecting setuptools
  Using cached setuptools-58.2.0-py3-none-any.whl (946 kB)
WARNING: Error parsing requirements for sloth-ci: Parse error at "'[Colored'": Expected stringEnd
Installing collected packages: setuptools
Successfully installed setuptools-58.2.0
WARNING: You are using pip version 21.0.1; however, version 21.3 is available.
You should consider upgrading via the '/home/vh/.cache/pypoetry/virtualenvs/sloth-ci-gF8KaH2q-py3.9/bin/python -m pip install --upgrade pip' command.
vh@box ~/ci/sloth-ci [master][n] % poetry run foliant make site -p docs
Parsing config... Done
Applying preprocessor includes... Done
Applying preprocessor superlinks... Preprocessor superlinks is not installed
Applying preprocessor mkdocs... Done
Applying preprocessor _unescape... Done
Making site with MkDocs... Done
────────────────────
Result: sloth-ci-docs.mkdocs
```

Then the foliant superlinks preprocessor is not installed and pip is not up to date.

**Comment by inktrap** [comment]
Also this:

```
WARNING: Error parsing requirements for sloth-ci: Parse error at "'[Colored'": Expected stringEnd
```

But I guess it is just from an outdated pip version which I updated :

```
poetry run pip install --upgrade pip
```

**Comment by moigagoo** [comment]
@inktrap what version of Poetry are you on? I think I've encountered this error before but switching to Poetry 1.2 (aka master) fixed the problem.

**Comment by inktrap** [comment]
My poetry version was:

***@***.*** ~/ci/sloth-ci [master][i] % poetry --version
Poetry version 1.1.7


I updated to  1.1.11 which was released ~15 days ago
is 1.2 a pre-release version?

<https://github.com/python-poetry/poetry>

With 1.1.11 the problem still persists.
Might be this bug: <https://github.com/python-poetry/poetry/issues/1584>

**Comment by moigagoo** [comment]
Yes, 1.2 is a pre-release and it has been for quite some time. It's pretty stable and fixes a few issues.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by inktrap** [comment]
So with Poetry (version 1.2.0a2) it works :) let's update the docs?

Also I'll get asked for username/password when building the docs:

```
***@***.*** ~/ci/sloth-ci [develop][i] % poetry run foliant make site -p docs
Parsing config... Done
Applying preprocessor includes... Username for 'https://github.com': 
Password for 'https://github.com': 
Failed to apply preprocessor includes: [Errno 2] No such file or directory: '/home/vh/ci/sloth-ci/docs/.includescache/sloth-ci-ext-docker/README.md'
Applying preprocessor superlinks... Done
Applying preprocessor mkdocs... Done
Applying preprocessor _unescape... Done
Making site with MkDocs... Done
────────────────────
Result: sloth-ci-docs.mkdocs
```

**Comment by moigagoo** [comment]
> let's update the docs?

Sure, feel free to submit a PR.

> Also I'll get asked for username/password when building the docs:

Hmmm, this is weird. Also, it's weird there's an attempt to clone the docker extension docs, there is no repo for it. Try updating the repo to the latest develop, remove .includescache, and try again.

**Comment by inktrap** [comment]
Deleting ``includescache`` and pulling worked!
